project_id = "ckzystwcwufvarektakc"

[global]
[global.env]
OPENAI_API_KEY = "{{env.OPENAI_API_KEY}}"
RESEND_API_KEY = "{{env.RESEND_API_KEY}}"

[[functions]]
name = "analyze-content"
verify_jwt = true

[[functions]]
name = "send-notification"
verify_jwt = true

[[functions]]
name = "analyze-document"
verify_jwt = true