
project_id = "dvflgnqwbsjityrowatf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://ai.ctnigeria.com"
additional_redirect_urls = ["https://ai.ctnigeria.com", "https://ai.ctnigeria.com/auth/callback"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_refresh_token_reuse_interval = 10
enable_anonymous_sign_ins = false

[functions.ai-chat]
verify_jwt = true

[functions.send-notification]
verify_jwt = true

[functions.analyze-and-notify]
verify_jwt = true
