// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckzystwcwufvarektakc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrenlzdHdjd3VmdmFyZWt0YWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNjU5NjcsImV4cCI6MjA1MTg0MTk2N30.TubhsmQR1Q2H8aB3c4aH1nBkTLYsV1EOI3zhTw5TVtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);